title: Asarbaev A. A.
description: > # this means to ignore newlines until "baseurl:"
  Data Science blog
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Amir Asarbaev # add your name
author-img: asarbaev_a.jpg # add your photo
about-author: Hello everyone! My name is Amir. I'm a graduate student in Data Science at ENSIMAG engineering school of Grenoble. Here you can explore my projects. # add description

social-github: asarbaev # add your Github handle
social-linkedin: amir-asarbaev # add your Linkedin handle
social-email: asarbaevamir@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: "UA-116902624-1" # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
